// Category Type
export const ALL_CATEGORIES_REQUEST = "ALL_CATEGORIES_REQUEST"
export const ALL_CATEGORIES_REQUEST_SUCCESS = "ALL_CATEGORIES_REQUEST_SUCCESS"
export const ALL_CATEGORIES_REQUEST_FAILED = "ALL_CATEGORIES_REQUEST_FAILED"

// Get products by slug
export const GET_PRODUCTS_BY_SLUG_REQUEST = 'GET_PRODUCTS_BY_SLUG_REQUEST';
export const GET_PRODUCTS_BY_SLUG_REQUEST_SUCCESS = 'GET_PRODUCTS_BY_SLUG_REQUEST_SUCCESS';
export const GET_PRODUCTS_BY_SLUG_REQUEST_FAILED = 'GET_PRODUCTS_BY_SLUG_REQUEST_FAILED';