// Category Type
export const ALL_CATEGORIES_REQUEST = "ALL_CATEGORIES_REQUEST"
export const ALL_CATEGORIES_REQUEST_SUCCESS = "ALL_CATEGORIES_REQUEST_SUCCESS"
export const ALL_CATEGORIES_REQUEST_FAILED = "ALL_CATEGORIES_REQUEST_FAILED"

// Get products by slug
export const GET_PRODUCTS_BY_SLUG_REQUEST = 'GET_PRODUCTS_BY_SLUG_REQUEST';
export const GET_PRODUCTS_BY_SLUG_REQUEST_SUCCESS = 'GET_PRODUCTS_BY_SLUG_REQUEST_SUCCESS';
export const GET_PRODUCTS_BY_SLUG_REQUEST_FAILED = 'GET_PRODUCTS_BY_SLUG_REQUEST_FAILED';
export const GET_PRODUCTS_BY_PAGE_REQUEST = "GET_PRODUCTS_BY_PAGE_REQUEST";
export const GET_PRODUCTS_BY_PAGE_REQUEST_SUCCESS = "GET_PRODUCTS_BY_PAGE_REQUEST_SUCCESS";
export const GET_PRODUCTS_BY_PAGE_REQUEST_FAILED = "GET_PRODUCTS_BY_PAGE_REQUEST_FAILED";

// productsConstants
export const productsConstants = {
    PRODUCT_BY_ID_REQUEST: "PRODUCT_BY_ID_REQUEST",
    PRODUCT_BY_ID_SUCCESS: "PRODUCT_BY_ID_SUCCESS" ,
    PRODUCT_BY_ID_FAILURE: "PRODUCT_BY_ID_FAILURE" ,
}



// Auth Type
export const authConstants = {
    LOGIN_REQUEST: "LOGIN_REQUEST",
    LOGIN_SUCESS: "LOGIN_SUCESS",
    LOGIN_FALIURE: "LOGIN_FALIURE",
    SIGINUP_REQUEST: "SIGINUP_REQUEST",
    SIGINUP_SUCCESS: "SIGINUP_SUCCESS",
    SIGINUP_FALIURE: "SIGINUP_FALIURE",
}


// Cart Type
export const cartConstants = {
    ADD_TO_CART:'ADD_TO_CART',
    CART_RESET:'CART_RESET'
}


// Adress Type
export const addressConstants = {
    ADDRESS_REQUEST: "ADDRESS_REQUEST",
    ADDRESS_SUCCESS: "ADDRESS_SUCCESS",
    ADDRESS_FAILURE: "ADDRESS_FAILURE",
    ADD_ADDRESS_REQUEST: "ADD_ADDRESS_REQUEST",
    ADD_ADDRESS_SUCCESS: "ADD_ADDRESS_SUCCESS",
    ADD_ADDRESS_FAILURE: "ADD_ADDRESS_FAILURE"
}
// Order Type
export const orderConstants = {
    ADD_ORDER_REQUEST:"ORDER_ADD_REQUEST",
    ADD_ORDER_SUCCESS:"ORDER_ADD_SUCCESS",
    ADD_ORDER_FAILURE:"ORDER_ADD_FAILURE"
}